### ISSUE TITLE
How do you view the profile?

### ISSUE THREAD

**Issue by Tomas1337** [sunhailin-Leo/fastapi_profiler#1]
With pyinstrument, the results show upon finishing/closing.
When running through the command line and using `uvicorn`, where do you view the profile?

**Comment by sunhailin-Leo** [comment]
@Tomas1337 
* Save to `html` or print it on commander/console

**Comment by sunhailin-Leo** [comment]
@Tomas1337 
* Here is the source code. https://github.com/sunhailin-Leo/fastapi_profiler/blob/main/fastapi_profiler/profiler_middleware/profiler.py#L74
