### ISSUE TITLE
Runtime Error: This profiler is not currently running

### ISSUE THREAD

**Issue by liongkj** [sunhailin-Leo/fastapi_profiler#12]
This is my first time using a profiler, how do i make the profiler run? This is how i add the middleware

```python 
if app_config.PROFILE_MODE:
    print("__________________profile mode__________________")

    from fastapi_profiler import PyInstrumentProfilerMiddleware

    app.add_middleware(
        PyInstrumentProfilerMiddleware,
        server_app=app,  # Required to output the profile on server shutdown
        profiler_output_type="html",
        is_print_each_request=False,  # Set to True to show request profile on
        # stdout on each request
        open_in_browser=True,  # Set to true to open your web-browser automatically
        # when the server shuts down
        html_file_name="example_profile.html",  # Filename for output)
    )
```

**Comment by ndejong** [comment]
+1 similar issue, although in my case `fastapi_profiler` was working earlier in the development cycle with the project.  Certainly seems like something has been added to the project that is now making `fastapi_profiler` unhappy, but I can't yet find the root-cause by stripping everything back etc

* fastapi==0.92.0
* fastapi-profiler==1.1.0
* starlette==0.25.0
* uvicorn==0.20.0


```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/fastapi_profiler/profiler.py", line 77, in __call__
    self._profiler.stop()
  File "/home/user/.local/venvs/awesome-api/lib/python3.10/site-packages/pyinstrument/profiler.py", line 144, in stop
    raise RuntimeError("This profiler is not currently running.")
RuntimeError: This profiler is not currently running.
```

**Comment by ikrutik** [comment]
I have the same error

**Comment by olehusov** [comment]
same hear

**Comment by PeterSR** [comment]
same

**Comment by lifeiteng** [comment]
也遇到了这个错误

@sunhailin-Leo 可以修复下吗

**Comment by lifeiteng** [comment]
set `async_mode="strict"` https://pyinstrument.readthedocs.io/en/latest/reference.html#pyinstrument.Profiler.async_mode
```
app.add_middleware(
    PyInstrumentProfilerMiddleware,
    server_app=app,  # Required to output the profile on server shutdown
    profiler_output_type="html",
    is_print_each_request=False,  # Set to True to show request profile on
                                  # stdout on each request
    open_in_browser=False,  # Set to true to open your web-browser automatically
                            # when the server shuts down
    async_mode="strict",
    html_file_name="example_profile.html"  # Filename for output
)
```

**Comment by sunhailin-Leo** [comment]
What OS did you use?
* fastapi, pyinstructment, fastapi-profiler are latest version
* I tested it on Windows 11(with WSL2) and MacOS, with Python 3.7 and Python 3.10. it doesn`t meet this error.

**Comment by nhhviet98** [comment]
@sunhailin-Leo 

I have the same issue when profiling with high-concurrent users (using `locust`), it works fine if I call requests sequentially (CCU = 1). 

Can this problem be fixed? or any suggestions if I want to profile my FastAPI Server with accumulative metrics from multiple requests in high-concurrent users context?

**Comment by sunhailin-Leo** [comment]
@nhhviet98 
* Did you try this `async_mode="strict"` ?

**Comment by nhhviet98** [comment]
> @nhhviet98
> 
> * Did you try this `async_mode="strict"` ?

Yes, I tried. I also try with fastapi_profiler `1.4.1` and `1.2.0` but it also has the same error log.

**Comment by sunhailin-Leo** [comment]
> > @nhhviet98
> > 
> > * Did you try this `async_mode="strict"` ?
> 
> Yes, I tried. I also try with fastapi_profiler `1.4.1` and `1.2.0` but it also has the same error log.

I'm not quite sure how you're using the profiler middleware, but I'm not reproducing the issue in my local environment. Can you provide me with your environment and deployment information?

**Comment by nhhviet98** [comment]
@sunhailin-Leo 

After some debugging steps, I rewrote a simple FastAPI app from my scenarios. The difference with [this example](https://github.com/sunhailin-Leo/fastapi_profiler/blob/main/example/fastapi_to_html_example.py) is my endpoint has some asynchronous function, so 1 FastAPI worker can handle multiple requests at the same time. And profiler `Failed to stop profiling`.

I also realized that the error rate increases as concurrent users increase. (using `locust` to increase CCU)

**This is my simple FastAPI application:**

```python
import asyncio
import uvicorn

from fastapi import FastAPI
from fastapi_profiler import PyInstrumentProfilerMiddleware

app = FastAPI()

app.add_middleware(
    PyInstrumentProfilerMiddleware,
    server_app=app,  # Required to output the profile on server shutdown
    profiler_output_type="html",
    is_print_each_request=True,  # Set to True to show request profile on
    # stdout on each request
    open_in_browser=True,  # Set to true to open your web-browser automatically
    # when the server shuts down
    async_mode="strict",
    html_file_name="example_profile.html"  # Filename for outputFilename for output
)

@app.get("/items")
async def read_item():
    await asyncio.sleep(1)  # Simulating an async task
    return {"message": "This is an async response"}


if __name__ == "__main__":
    uvicorn.run(
        "app.main:app",
        host="0.0.0.0",
        port=3014,
        log_level="info",
        workers=1
    )

```

**Dependencies:**
- fastapi_profiler==1.4.1
- pyinstrument==4.6.0
- fastapi==0.101.0

---

Thank you so much for your enthusiastic support. 💯

**Comment by sunhailin-Leo** [comment]
@nhhviet98 
* This problem does occur when you are using `asyncio.sleep`. However, I don't think you should use the `asyncio.sleep` function to reproduce this problem. Because the implementation logic of `asyncio.sleep` is not comparable to asynchronous tasks used in real scenarios.
* You can check `asyncio.sleep` source code
![image](https://github.com/sunhailin-Leo/fastapi_profiler/assets/17564655/2ab1aa21-355a-4b7f-beb2-70351e043d9f)

**Comment by sunhailin-Leo** [comment]
@nhhviet98 
* Personally, I think it's because `events.TimerHandle` used within `asyncio.sleep` causes the currently running coroutine to hang, which allows the Profiler to catch the coroutine as not being an active session which ultimately leads to an error in the middleware call.

**Comment by nhhviet98** [comment]
@sunhailin-Leo 

As I mentioned above, `asyncio.sleep()` that I've used only for simplicity. In my reality scenario, `async def` is for downloading an image from a public URL asynchronously.

I think that (may not be accurate) because when a FastAPI worker handles 2 requests simultaneously (because I use async in my router), after request 1 calls `self._stop_profiler`, request 2 also calls `self._stop_profiler` after that (when the profiler is stopped) => It's raise this error in middleware.

---

I'm not too sure about my opinion so please give me your opinion (if you have a solution, that would be even better 😍)

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo
> 
> As I mentioned above, `asyncio.sleep()` that I've used only for simplicity. In my reality scenario, `async def` is for downloading an image from a public URL asynchronously.
> 
> I think that (may not be accurate) because when a FastAPI worker handles 2 requests simultaneously (because I use async in my router), after request 1 calls `self._stop_profiler`, request 2 also calls `self._stop_profiler` after that (when the profiler is stopped) => It's raise this error in middleware.
> 
> I'm not too sure about my opinion so please give me your opinion (if you have a solution, that would be even better 😍)

* Does this issue occur if you add a Profiler test when accessing an external URL using `async def`?

**Comment by sunhailin-Leo** [comment]
@nhhviet98 
* My opinion is that there is no need to use `asyncio.sleep` as a test, but use real code logic to find the part that takes the longest.
This is the scenario where Profiler should really be used.

**Comment by nhhviet98** [comment]
> > @sunhailin-Leo
> > As I mentioned above, `asyncio.sleep()` that I've used only for simplicity. In my reality scenario, `async def` is for downloading an image from a public URL asynchronously.
> > I think that (may not be accurate) because when a FastAPI worker handles 2 requests simultaneously (because I use async in my router), after request 1 calls `self._stop_profiler`, request 2 also calls `self._stop_profiler` after that (when the profiler is stopped) => It's raise this error in middleware.
> > I'm not too sure about my opinion so please give me your opinion (if you have a solution, that would be even better 😍)
> 
> * Does this issue occur if you add a Profiler test when accessing an external URL using `async def`?

Yes, this issue also occurs.

---

> @nhhviet98
> 
> * My opinion is that there is no need to use `asyncio.sleep` as a test, but use real code logic to find the part that takes the longest.
>   This is the scenario where Profiler should really be used.

I see what you mean, my scenario is profiling my FastAPI server with high CCU and finding what bottleneck in my code, with the latest version of `fastapi_profiler`, it can work if I don't use `async def` in my code.

Any suggestion for me :(

**Comment by sunhailin-Leo** [comment]
@nhhviet98 
* I found the problem. The main reason is that `pyinstrument` is thread-unsafe in getting stack information in concurrent scenarios, so sequential calls don't cause problems, concurrent calls do.
* Next I tried to see how to fix the problem.

**Comment by nhhviet98** [comment]
@sunhailin-Leo

Any update on this issue?

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo
> 
> Any update on this issue?

If the Profiler is created on a per-request basis, you won't have this problem. But how about putting it at global initialisation when that problem occurs in concurrent scenarios.

**Comment by shrey1605** [comment]
@sunhailin-Leo I am encountering the same error. You said that if profiler is created on a per-request basis, this won't be a problem. Any idea how to do that? Also, wouldn't the overhead be a little bit more if we're doing that?
