### ISSUE TITLE
Output to json speedscope

### ISSUE THREAD

**Issue by Joel-eGarcia** [sunhailin-Leo/fastapi_profiler#15]
json output format can be supported, just html and prof are available. 

something like this:
```python
app.add_middleware(
    PyInstrumentProfilerMiddleware,
    profiler_output_type="json",
    prof_file_name="example_profile.json"
)`

**Comment by sunhailin-Leo** [comment]
@Joel-eGarcia 
* I will add this feature ASAP.

**Comment by sunhailin-Leo** [comment]
@Joel-eGarcia 
* https://github.com/sunhailin-Leo/fastapi_profiler/releases/tag/v1.3.0

**Comment by HCharlie** [comment]
I am uploading the json file generated by the json example to https://www.speedscope.app/, it shows below, any idea how to fix this?

![Screenshot 2024-04-27 at 21 44 15](https://github.com/sunhailin-Leo/fastapi_profiler/assets/18575426/e17457fb-a154-4074-8e9b-709f4b44f39d)
