### ISSUE TITLE
Add support for speedscope

### ISSUE THREAD

**Issue by kbhatiya999** [sunhailin-Leo/fastapi_profiler#16]
[Speedscope](https://www.speedscope.app/) is a great visualizer.
Take a look yourself : [https://calmcode.io/course/pyinstrument/speedscope](https://calmcode.io/course/pyinstrument/speedscope)

![image](https://github.com/sunhailin-Leo/fastapi_profiler/assets/47816034/cb928148-eedd-41a8-a862-4c20f35d3feb)

![image](https://github.com/sunhailin-Leo/fastapi_profiler/assets/47816034/66257ca0-7996-4eed-a46c-3aff711e2096)

**Comment by sunhailin-Leo** [comment]
@kbhatiya999 
* Coming soon~

**Comment by sunhailin-Leo** [comment]
@kbhatiya999 
* I will upload the wheel later~
