### ISSUE TITLE
TypeError: Profile.print_stats() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by PaleNeutron** [sunhailin-Leo/fastapi_profiler#18]
```
                    if self._output_type == "prof":
                        s = StringIO()
>                       self._profiler.print_stats(stream=s)
E                       TypeError: Profile.print_stats() got an unexpected keyword argument 'stream'
```

**Comment by sunhailin-Leo** [comment]
@PaleNeutron 
* Tell me all dependency versions.

**Comment by PaleNeutron** [comment]
```
Name: fastapi_profiler
Version: 1.4.1

Name: fastapi
Version: 0.110.3

Name: pyinstrument
Version: 5.0.0
```

**Comment by sunhailin-Leo** [comment]
@PaleNeutron 
* Which Python version do you use?

**Comment by PaleNeutron** [comment]
Python 3.10

**Comment by sunhailin-Leo** [comment]
@PaleNeutron 
* I tested it on `Windows (also WSL2)，Python 3.10.12，fastapi==0.111.0，fastapi_profiler==1.4.1，pyinstrument==5.0.0`，but not reproduce your question.
* It would be nice to have more detailed information about your environment~

**Comment by PaleNeutron** [comment]
My os is ubuntu 22.04.

**Comment by sunhailin-Leo** [comment]
> My os is ubuntu 22.04.

* My WSL2 is also ubuntu 22.04. But I cannot reproduce it.

**Comment by tavo-uemg** [comment]
I'm having the same issue when i use it with `profiler_output_type='prof'`. I see the code where the error happen `self._profiler.print_stats(stream=s)` and in the print_stats definition and don't get any argument called stream

```python
# cProfile.py
    def print_stats(self, sort=-1):
        import pstats
        pstats.Stats(self).strip_dirs().sort_stats(sort).print_stats()
```
