### ISSUE TITLE
How to read/interpret the data of how much memory was consumed by the API?

### ISSUE THREAD

**Issue by directlinks** [sunhailin-Leo/fastapi_profiler#2]
This is what the result looks like-
![image](https://user-images.githubusercontent.com/29857759/110957230-6f7df180-8371-11eb-8bd3-e8b22a36efb0.png)

But I am unable to interpret this data, how do you know how much memory was consumed by the API from the above-mentioned data?

**Comment by sunhailin-Leo** [comment]
@directlinks This project is based on `pyinstrument` https://github.com/joerick/pyinstrument
