### ISSUE TITLE
How you can save output to csv or log it in more readable way

### ISSUE THREAD

**Issue by sandeeppilania** [sunhailin-Leo/fastapi_profiler#3]
`app = FastAPI()`
`app.add_middleware(PyInstrumentProfilerMiddleware)`

Provides something like this 
![image](https://user-images.githubusercontent.com/38011316/112585090-88ee5700-8dcf-11eb-85ce-92b9c6068600.png)

How we can get it in more readable way or save to html/logs , can you share an example ?

**Comment by sunhailin-Leo** [comment]
@sandeeppilania 
* It can be save to html.
* You can pass some arguments to save html, after reading the source code. https://github.com/sunhailin-Leo/fastapi_profiler/blob/main/fastapi_profiler/profiler_middleware/profiler.py#L77
