### ISSUE TITLE
Output to html

### ISSUE THREAD

**Issue by Dirt-Nasty** [sunhailin-Leo/fastapi_profiler#6]
I am passing in the proper argument i believe but I can't find the html file

`app.add_middleware(PyInstrumentProfilerMiddleware, profiler_output_type='html')`

**Comment by sunhailin-Leo** [comment]
@Dirt-Nasty 
* You need pass a argument like this: https://github.com/sunhailin-Leo/fastapi_profiler/blob/main/fastapi_profiler/profiler_middleware/profiler.py#L78
