### ISSUE TITLE
Feature request: .prof output to interface with visualisation tool like snakeviz

### ISSUE THREAD

**Issue by weiann-tractable** [sunhailin-Leo/fastapi_profiler#9]
Hello! Thanks for making this great project, I think this is the best profiler for Fast API applications out there.

One feature that would be super useful is outputting the profiles in a format like `.prof` that can be used by visualisation tools like `snakeviz`. This is one of the outputs of Python's `cProfile` and implemented by werkzeug which Flask is built on. ([cProfile docs](https://docs.python.org/3/library/profile.html),  [profiling in flask applications that produce .prof files](https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-xvi-debugging-testing-and-profiling))

Adding the ability to visualise these profiles would really increase the impact of this tool!

**Comment by msnidal** [comment]
Hello, I have put up a PR that implements this! Feel free to try it out at [my fork and branch](https://github.com/msnidal/fastapi_profiler/tree/feature/dot-prof-support) if you like, otherwise hopefully the maintainer will be able to take a look
